cacti:
  image: quantumobject/docker-cacti
  ports:
   - "80:80"
   - "161:161"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ./plugins/:/opt/cacti/plugins/
   - ./log/:/var/log/
   - ./templates/:/opt/cacti/templates/
   - ./mysql/:/var/lib/mysql/
   - ./rra/:/opt/cacti/rra/
